import "@/styles/globals.scss";
import "@arco-design/web-react/dist/css/arco.css";

import { Inter } from "next/font/google";
import Container from "@/components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ursazoo | 熊熊动物园",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
